### ISSUE TITLE
Error while building aws-rds

### ISSUE THREAD

**Issue by smondet** [inhabitedtype/ocaml-aws#25]
Pinned to `master`, for `opam install aws-rds` I get:

```
+ /home/smondet/.opam/4.03.0/bin/ocamlfind ocamlc -c -g -annot -bin-annot -package aws -I lib -o lib/describeAccountAttributes.cmi lib/describeAccountAttributes.mli
File "lib/describeAccountAttributes.mli", line 2, characters 13-47:
Error: Unbound module DescribeAccountAttributesMessage
Command exited with code 2.
```

**Comment by tmcgilchrist** [comment]
This is a bug in the code generation.

There is a message for this defined in the service-2.json for RDS [1]. The message is slightly unusual in that it doesn't have anything in the message body. Something like:

```ocaml
module DescribeAccountAttributesMessage =
struct
  type t = unit

  let to_query _v = Query.List []
end
```
compiles but I haven't got any test cases to run it against to check whether it does the right thing.
And whether the empty Query.list gets reduced to the empty string.
Looking at `amazonka` and how it handles messages like this was helpful, there they just output `version` and `action` attributes. [2]

A better option I think would be for the OCaml code to do that directly rather than having a noop/null message.
```ocaml
let to_http req =
  let uri =
    Uri.add_query_params (Uri.of_string "https://rds.amazonaws.com")
      ([("Version", ["2014-10-31"]);
         ("Action", ["DescribeAccountAttributes"])])
     in
  (`POST, uri, [])
```

Right now I am working on the jbuilder port and haven't gone any further in fixing the generator.


[1]
```
    "DescribeAccountAttributes":{
      "name":"DescribeAccountAttributes",
      "http":{
        "method":"POST",
        "requestUri":"/"
      },
      "input":{
        "shape":"DescribeAccountAttributesMessage",
        "documentation":"<p></p>"
      },
      "output":{
        "shape":"AccountAttributesMessage",
        "documentation":"<p>Data returned by the <b>DescribeAccountAttributes</b> action.</p>",
        "resultWrapper":"DescribeAccountAttributesResult"
      },

...

    "DescribeAccountAttributesMessage":{
      "type":"structure",
      "members":{
      },
      "documentation":"<p></p>"
```

[2] https://github.com/brendanhay/amazonka/blob/develop/amazonka-rds/gen/Network/AWS/RDS/DescribeAccountAttributes.hs#L86-L92

**Comment by tmcgilchrist** [comment]
Release pending the merge of build system port to jbuilder and various generator fixes.
