### ISSUE TITLE
Where are the modules

### ISSUE THREAD

**Issue by fxfactorial** [inhabitedtype/ocaml-aws#8]
Thanks for this! I had a similar idea a year ago but wasn't good enough at that time to make it work.

Installed a fresh copy directly via pinning, using lwt, and I'm not getting the `Aws_ec2` module. At the top level I only get Aws, Aws_lwt and Aws_gen.

**Comment by seliopou** [comment]
In order to install the EC2 bindings, go to the `libraries/ec2` and pin the package there. This package will expose a module called `Aws_ec2` under which you find a `Types` module and a module for each API call in the service.

The ec2 package along the others will be published shortly. Still working on some automation for the release process.
