### ISSUE TITLE
Missing result module for ec2?

### ISSUE THREAD

**Issue by fxfactorial** [inhabitedtype/ocaml-aws#9]
Simple code for describeimagesresult

```ocaml
  | `Ok r ->
    let (b : Yojson.Basic.json) =
      Aws_ec2.Types.DescribeImagesResult.to_json r
    in
    Yojson.Basic.pretty_to_string b
    |> Lwt_io.printl
  | `Error oops ->
    Aws.Error.format Aws_ec2.Errors.to_string oops |> Lwt_io.printl
```

I need something similar for Aws_ec2.CreateVolume, currently have:

```ocaml
let do_run =
  let (access_key, secret_key) = keys () in
  Aws_lwt.Runtime.run_request
    (* Need to pick the appropriate region, won't work with a wrong
         region *)
    ~region:"us-east-1"
    ~access_key
    ~secret_key

let do_create_volume () =
  do_run
    (module Aws_ec2.CreateVolume)
    (Aws_ec2.Types.CreateVolumeRequest.make
       ~dry_run:true
       ~availability_zone:"us-east-1"
       ()) >>= function
  | `Ok r ->
.... But Aws_ec2.Types.CreateVolumeResult does not exist.
  | `Error oops ->
    Lwt_io.printl "Done"
```

So how can I get a result? I understand the code is auto generated but does that mean that the ec2 bindings are incomplete at the moment?

**Comment by seliopou** [comment]
Check `Aws_ec2.CreateVolume.output` to find the output type of the API.

The EC2 bindings in particular have a lot of a lot of API calls with apt of types and a lot of fields. I highly encourage consumers of this library to use Merlin to help navigate it all.

**Comment by fxfactorial** [comment]
@seliopou Thanks, I am aware of merlin and other tools and I am aware of the type, however I gave code examples that seemingly show an inconsistency in the API.

Would it be too much to ask that issues not be closed before knowing that end user is actually succeeding?

**Comment by seliopou** [comment]
The module names used by the bindings are the names of the types provided by the botocore service descriptions. The naming is unfortunate, but changing them in these bindings would probably do more harm than good knowledge sharing amongst the sea documentation and other libraries.

With respect to closing the issue, I'm sorry it came off wrong but I assure you I don't deal in passive-aggressive issue tracking. As I understood the issue, you seemed to imply that a module that you thought should exist didn't exist under any name rather than simply not having the right name. Given that I was certain that my answer was correct and would ensure that you succeed in finishing your code snippet. Closing an issue, for me at least, doesn't end the conversation. It simply indicates that the code tasks doesn't not need attention based on the issue. Does that make sense?

I hope you'll continue to engage with the project.

-Spiros E.

i sent this from my Phone.

**Comment by fxfactorial** [comment]
@seliopou Ah, much appreciated. I'll continue with it, will have to dig some more then, maybe when working will submit PR for code examples.
